
/**************************************************************
 *	
 *	SelectSound, 8 bit, 11025Hz,
 *	1 channel, 2523 bytes/channel
 *	Total Size: 1 * 2523 + 4 (header) = 2567 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/MenuSounds/Output/SelectSound.wav
 *	Time-stamp: Fri Apr 06 23:26:30 2018
 *	
 **************************************************************/

#ifndef __SELECTSOUNDH__
#define __SELECTSOUNDH__

#define SELECTSOUNDFREQ 11025
#define SELECTSOUNDLEN 2523

extern const unsigned char SelectSound[2523];

#endif /* __SELECTSOUNDH__ */
