
/**************************************************************
 *	
 *	StartSound, 8 bit, 11025Hz,
 *	1 channel, 5746 bytes/channel
 *	Total Size: 1 * 5746 + 4 (header) = 5790 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/MenuSounds/Output/StartSound.wav
 *	Time-stamp: Fri Apr 06 23:26:36 2018
 *	
 **************************************************************/

#ifndef __STARTSOUNDH__
#define __STARTSOUNDH__

#define STARTSOUNDFREQ 11025
#define STARTSOUNDLEN 5746

extern const unsigned char StartSound[5746];

#endif /* __STARTSOUNDH__ */
