
/**************************************************************
 *	
 *	InstructionsMusic, 8 bit, 11025Hz,
 *	1 channel, 389543 bytes/channel
 *	Total Size: 1 * 389543 + 4 (header) = 389587 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/InstructionsMusic.wav
 *	Time-stamp: Fri Apr 06 19:46:26 2018
 *	
 **************************************************************/

#ifndef __INSTRUCTIONSMUSICH__
#define __INSTRUCTIONSMUSICH__

#define INSTRUCTIONSMUSICFREQ 11025
#define INSTRUCTIONSMUSICLEN 389543

extern const unsigned char InstructionsMusic[389543];

#endif /* __INSTRUCTIONSMUSICH__ */
