
/**************************************************************
 *
 *	TitleMusic4, 8 bit, 11025Hz,
 *	1 channel, 956736 bytes/channel
 *	Total Size: 1 * 956736 + 4 (header) = 956780 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/TitleMusic4.wav
 *	Time-stamp: Fri Apr 06 19:24:30 2018
 *
 **************************************************************/

#ifndef __TITLEMUSIC4H__
#define __TITLEMUSIC4H__

#define TITLEMUSIC4FREQ 11025
#define TITLEMUSIC4LEN 956736

extern const unsigned char TitleMusic4[956736];

#endif /* __TITLEMUSIC4H__ */

/**************************************************************
 *
 *	InstructionsMusic, 8 bit, 11025Hz,
 *	1 channel, 389543 bytes/channel
 *	Total Size: 1 * 389543 + 4 (header) = 389587 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/InstructionsMusic.wav
 *	Time-stamp: Fri Apr 06 19:46:26 2018
 *
 **************************************************************/

#ifndef __INSTRUCTIONSMUSICH__
#define __INSTRUCTIONSMUSICH__

#define INSTRUCTIONSMUSICFREQ 11025
#define INSTRUCTIONSMUSICLEN 389543

extern const unsigned char InstructionsMusic[389543];

#endif /* __INSTRUCTIONSMUSICH__ */

/**************************************************************
 *
 *	TitleMusic2, 8 bit, 11025Hz,
 *	1 channel, 1709020 bytes/channel
 *	Total Size: 1 * 1709020 + 4 (header) = 1709064 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/TitleMusic2.wav
 *	Time-stamp: Fri Apr 06 19:51:18 2018
 *
 **************************************************************/

#ifndef __TITLEMUSIC2H__
#define __TITLEMUSIC2H__

#define TITLEMUSIC2FREQ 11025
#define TITLEMUSIC2LEN 1709020

extern const unsigned char TitleMusic2[1709020];

#endif /* __TITLEMUSIC2H__ */

/**************************************************************
 *
 *	AudienceSounds, 8 bit, 11025Hz,
 *	1 channel, 60458 bytes/channel
 *	Total Size: 1 * 60458 + 4 (header) = 60502 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/AudienceSounds.wav
 *	Time-stamp: Sat Apr 07 15:50:59 2018
 *
 **************************************************************/

#ifndef __AUDIENCESOUNDSH__
#define __AUDIENCESOUNDSH__

#define AUDIENCESOUNDSFREQ 11025
#define AUDIENCESOUNDSLEN 60458

extern const unsigned char AudienceSounds[60458];

#endif /* __AUDIENCESOUNDSH__ */

/**************************************************************
 *
 *	ChampKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151883 bytes/channel
 *	Total Size: 1 * 151883 + 4 (header) = 151927 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/ChampKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:23 2018
 *
 **************************************************************/

#ifndef __CHAMPKNOCKDOWNMUSICH__
#define __CHAMPKNOCKDOWNMUSICH__

#define CHAMPKNOCKDOWNMUSICFREQ 11025
#define CHAMPKNOCKDOWNMUSICLEN 151883

extern const unsigned char ChampKnockDownMusic[151883];

#endif /* __CHAMPKNOCKDOWNMUSICH__ */

/**************************************************************
 *
 *	MatchFightMusic, 8 bit, 11025Hz,
 *	1 channel, 685237 bytes/channel
 *	Total Size: 1 * 685237 + 4 (header) = 685281 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/MatchFightMusic.wav
 *	Time-stamp: Sat Apr 07 15:50:52 2018
 *
 **************************************************************/

#ifndef __MATCHFIGHTMUSICH__
#define __MATCHFIGHTMUSICH__

#define MATCHFIGHTMUSICFREQ 11025
#define MATCHFIGHTMUSICLEN 685237

extern const unsigned char MatchFightMusic[685237];

#endif /* __MATCHFIGHTMUSICH__ */

/**************************************************************
 *
 *	PlayerKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151488 bytes/channel
 *	Total Size: 1 * 151488 + 4 (header) = 151532 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/PlayerKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:07 2018
 *
 **************************************************************/

#ifndef __PLAYERKNOCKDOWNMUSICH__
#define __PLAYERKNOCKDOWNMUSICH__

#define PLAYERKNOCKDOWNMUSICFREQ 11025
#define PLAYERKNOCKDOWNMUSICLEN 151488

extern const unsigned char PlayerKnockDownMusic[151488];

#endif /* __PLAYERKNOCKDOWNMUSICH__ */

/**************************************************************
 *
 *	UltraFightMusic, 8 bit, 11025Hz,
 *	1 channel, 1167938 bytes/channel
 *	Total Size: 1 * 1167938 + 4 (header) = 1167982 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/UltraFightMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:12 2018
 *
 **************************************************************/

#ifndef __ULTRAFIGHTMUSICH__
#define __ULTRAFIGHTMUSICH__

#define ULTRAFIGHTMUSICFREQ 11025
#define ULTRAFIGHTMUSICLEN 1167938

extern const unsigned char UltraFightMusic[1167938];

#endif /* __ULTRAFIGHTMUSICH__ */

/**************************************************************
 *
 *	CornerfaceAppears, 8 bit, 11025Hz,
 *	1 channel, 151833 bytes/channel
 *	Total Size: 1 * 151833 + 4 (header) = 151877 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceAppears.wav
 *	Time-stamp: Sun Apr 08 16:18:59 2018
 *
 **************************************************************/

#ifndef __CORNERFACEAPPEARSH__
#define __CORNERFACEAPPEARSH__

#define CORNERFACEAPPEARSFREQ 11025
#define CORNERFACEAPPEARSLEN 151833

extern const unsigned char CornerfaceAppears[151833];

#endif /* __CORNERFACEAPPEARSH__ */

/**************************************************************
 *
 *	CornerfaceChase, 8 bit, 11025Hz,
 *	1 channel, 306556 bytes/channel
 *	Total Size: 1 * 306556 + 4 (header) = 306600 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceChase.wav
 *	Time-stamp: Sun Apr 08 16:19:07 2018
 *
 **************************************************************/

#ifndef __CORNERFACECHASEH__
#define __CORNERFACECHASEH__

#define CORNERFACECHASEFREQ 11025
#define CORNERFACECHASELEN 306556

extern const unsigned char CornerfaceChase[306556];

#endif /* __CORNERFACECHASEH__ */

/**************************************************************
 *
 *	VictoryMusic, 8 bit, 11025Hz,
 *	1 channel, 76534 bytes/channel
 *	Total Size: 1 * 76534 + 4 (header) = 76578 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/VictoryMusic.wav
 *	Time-stamp: Wed Apr 11 16:11:18 2018
 *
 **************************************************************/

#ifndef __VICTORYMUSICH__
#define __VICTORYMUSICH__

#define VICTORYMUSICFREQ 11025
#define VICTORYMUSICLEN 76534

extern const unsigned char VictoryMusic[76534];

#endif /* __VICTORYMUSICH__ */

/**************************************************************
 *
 *	ThePromise, 8 bit, 11025Hz,
 *	1 channel, 2385697 bytes/channel
 *	Total Size: 1 * 2385697 + 4 (header) = 2385741 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/ThePromise.wav
 *	Time-stamp: Thu Apr 12 20:32:56 2018
 *
 **************************************************************/

#ifndef __THEPROMISEH__
#define __THEPROMISEH__

#define THEPROMISEFREQ 11025
#define THEPROMISELEN 2385697

extern const unsigned char ThePromise[2385697];

#endif /* __THEPROMISEH__ */


/**************************************************************
 *
 *	CornerfaceChase2, 8 bit, 11025Hz,
 *	1 channel, 144449 bytes/channel
 *	Total Size: 1 * 144449 + 4 (header) = 144493 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceChase2.wav
 *	Time-stamp: Sat Apr 14 11:35:43 2018
 *
 **************************************************************/

#ifndef __CORNERFACECHASE2H__
#define __CORNERFACECHASE2H__

#define CORNERFACECHASE2FREQ 11025
#define CORNERFACECHASE2LEN 144449

extern const unsigned char CornerfaceChase2[144449];

#endif /* __CORNERFACECHASE2H__ */

/**************************************************************
 *
 *	IntroMusic, 8 bit, 11025Hz,
 *	1 channel, 640372 bytes/channel
 *	Total Size: 1 * 640372 + 4 (header) = 640416 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/IntroMusic.wav
 *	Time-stamp: Sat Apr 14 20:27:25 2018
 *
 **************************************************************/

#ifndef __INTROMUSICH__
#define __INTROMUSICH__

#define INTROMUSICFREQ 11025
#define INTROMUSICLEN 640372

extern const unsigned char IntroMusic[640372];

#endif /* __INTROMUSICH__ */

/**************************************************************
 *
 *	IntroMontage, 8 bit, 11025Hz,
 *	1 channel, 92736 bytes/channel
 *	Total Size: 1 * 92736 + 4 (header) = 92780 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/IntroMontage.wav
 *	Time-stamp: Sat Apr 14 23:55:18 2018
 *
 **************************************************************/

#ifndef __INTROMONTAGEH__
#define __INTROMONTAGEH__

#define INTROMONTAGEFREQ 11025
#define INTROMONTAGELEN 92736

extern const unsigned char IntroMontage[92736];

#endif /* __INTROMONTAGEH__ */

/**************************************************************
 *
 *	SpreadWings, 8 bit, 11025Hz,
 *	1 channel, 1005408 bytes/channel
 *	Total Size: 1 * 1005408 + 4 (header) = 1005452 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/SpreadWings.wav
 *	Time-stamp: Sat Apr 14 23:55:26 2018
 *
 **************************************************************/

#ifndef __SPREADWINGSH__
#define __SPREADWINGSH__

#define SPREADWINGSFREQ 11025
#define SPREADWINGSLEN 1005408

extern const unsigned char SpreadWings[1005408];

#endif /* __SPREADWINGSH__ */
