
/**************************************************************
 *
 *	BlockSound, 8 bit, 11025Hz,
 *	1 channel, 5156 bytes/channel
 *	Total Size: 1 * 5156 + 4 (header) = 5200 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/BlockSound.wav
 *	Time-stamp: Fri Apr 06 20:58:39 2018
 *
 **************************************************************/

#ifndef __BLOCKSOUNDH__
#define __BLOCKSOUNDH__

#define BLOCKSOUNDFREQ 11025
#define BLOCKSOUNDLEN 5156

extern const unsigned char BlockSound[5156];

#endif /* __BLOCKSOUNDH__ */

/**************************************************************
 *
 *	ChampFeintSound, 8 bit, 11025Hz,
 *	1 channel, 5170 bytes/channel
 *	Total Size: 1 * 5170 + 4 (header) = 5214 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampFeintSound.wav
 *	Time-stamp: Fri Apr 06 20:59:32 2018
 *
 **************************************************************/

#ifndef __CHAMPFEINTSOUNDH__
#define __CHAMPFEINTSOUNDH__

#define CHAMPFEINTSOUNDFREQ 11025
#define CHAMPFEINTSOUNDLEN 5170

extern const unsigned char ChampFeintSound[5170];

#endif /* __CHAMPFEINTSOUNDH__ */

/**************************************************************
 *
 *	ChampPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 6971 bytes/channel
 *	Total Size: 1 * 6971 + 4 (header) = 7015 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound0.wav
 *	Time-stamp: Fri Apr 06 20:59:43 2018
 *
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND0H__
#define __CHAMPPUNCHSOUND0H__

#define CHAMPPUNCHSOUND0FREQ 11025
#define CHAMPPUNCHSOUND0LEN 6971

extern const unsigned char ChampPunchSound0[6971];

#endif /* __CHAMPPUNCHSOUND0H__ */

/**************************************************************
 *
 *	ChampPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5366 bytes/channel
 *	Total Size: 1 * 5366 + 4 (header) = 5410 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound1.wav
 *	Time-stamp: Fri Apr 06 20:59:52 2018
 *
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND1H__
#define __CHAMPPUNCHSOUND1H__

#define CHAMPPUNCHSOUND1FREQ 11025
#define CHAMPPUNCHSOUND1LEN 5366

extern const unsigned char ChampPunchSound1[5366];

#endif /* __CHAMPPUNCHSOUND1H__ */

/**************************************************************
 *
 *	ChampWindSound, 8 bit, 11025Hz,
 *	1 channel, 2958 bytes/channel
 *	Total Size: 1 * 2958 + 4 (header) = 3002 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampWindSound.wav
 *	Time-stamp: Fri Apr 06 20:59:58 2018
 *
 **************************************************************/

#ifndef __CHAMPWINDSOUNDH__
#define __CHAMPWINDSOUNDH__

#define CHAMPWINDSOUNDFREQ 11025
#define CHAMPWINDSOUNDLEN 2958

extern const unsigned char ChampWindSound[2958];

#endif /* __CHAMPWINDSOUNDH__ */

/**************************************************************
 *
 *	KOSound, 8 bit, 11025Hz,
 *	1 channel, 16645 bytes/channel
 *	Total Size: 1 * 16645 + 4 (header) = 16689 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/KOSound.wav
 *	Time-stamp: Fri Apr 06 21:00:05 2018
 *
 **************************************************************/

#ifndef __KOSOUNDH__
#define __KOSOUNDH__

#define KOSOUNDFREQ 11025
#define KOSOUNDLEN 16645

extern const unsigned char KOSound[16645];

#endif /* __KOSOUNDH__ */

/**************************************************************
 *
 *	PlayerDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 3511 bytes/channel
 *	Total Size: 1 * 3511 + 4 (header) = 3555 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerDodgeSound.wav
 *	Time-stamp: Fri Apr 06 21:00:28 2018
 *
 **************************************************************/

#ifndef __PLAYERDODGESOUNDH__
#define __PLAYERDODGESOUNDH__

#define PLAYERDODGESOUNDFREQ 11025
#define PLAYERDODGESOUNDLEN 3511

extern const unsigned char PlayerDodgeSound[3511];

#endif /* __PLAYERDODGESOUNDH__ */

/**************************************************************
 *
 *	PlayerPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 4984 bytes/channel
 *	Total Size: 1 * 4984 + 4 (header) = 5028 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound0.wav
 *	Time-stamp: Fri Apr 06 21:00:12 2018
 *
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND0H__
#define __PLAYERPUNCHSOUND0H__

#define PLAYERPUNCHSOUND0FREQ 11025
#define PLAYERPUNCHSOUND0LEN 4984

extern const unsigned char PlayerPunchSound0[4984];

#endif /* __PLAYERPUNCHSOUND0H__ */

/**************************************************************
 *
 *	PlayerPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5151 bytes/channel
 *	Total Size: 1 * 5151 + 4 (header) = 5195 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound1.wav
 *	Time-stamp: Fri Apr 06 21:00:20 2018
 *
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND1H__
#define __PLAYERPUNCHSOUND1H__

#define PLAYERPUNCHSOUND1FREQ 11025
#define PLAYERPUNCHSOUND1LEN 5151

extern const unsigned char PlayerPunchSound1[5151];

#endif /* __PLAYERPUNCHSOUND1H__ */

/**************************************************************
 *
 *	PlayerPunchSound2, 8 bit, 11025Hz,
 *	1 channel, 7876 bytes/channel
 *	Total Size: 1 * 7876 + 4 (header) = 7920 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound2.wav
 *	Time-stamp: Fri Apr 06 21:00:33 2018
 *
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND2H__
#define __PLAYERPUNCHSOUND2H__

#define PLAYERPUNCHSOUND2FREQ 11025
#define PLAYERPUNCHSOUND2LEN 7876

extern const unsigned char PlayerPunchSound2[7876];

#endif /* __PLAYERPUNCHSOUND2H__ */

/**************************************************************
 *
 *	CheatAura, 8 bit, 11025Hz,
 *	1 channel, 63489 bytes/channel
 *	Total Size: 1 * 63489 + 4 (header) = 63533 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatAura.wav
 *	Time-stamp: Fri Apr 06 22:40:18 2018
 *
 **************************************************************/

#ifndef __CHEATAURAH__
#define __CHEATAURAH__

#define CHEATAURAFREQ 11025
#define CHEATAURALEN 63489

extern const unsigned char CheatAura[63489];

#endif /* __CHEATAURAH__ */

/**************************************************************
 *
 *	CheatBlockSound, 8 bit, 11025Hz,
 *	1 channel, 2177 bytes/channel
 *	Total Size: 1 * 2177 + 4 (header) = 2221 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatBlockSound.wav
 *	Time-stamp: Fri Apr 06 22:39:55 2018
 *
 **************************************************************/

#ifndef __CHEATBLOCKSOUNDH__
#define __CHEATBLOCKSOUNDH__

#define CHEATBLOCKSOUNDFREQ 11025
#define CHEATBLOCKSOUNDLEN 2177

extern const unsigned char CheatBlockSound[2177];

#endif /* __CHEATBLOCKSOUNDH__ */

/**************************************************************
 *
 *	CheatDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 4634 bytes/channel
 *	Total Size: 1 * 4634 + 4 (header) = 4678 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatDodgeSound.wav
 *	Time-stamp: Fri Apr 06 22:40:09 2018
 *
 **************************************************************/

#ifndef __CHEATDODGESOUNDH__
#define __CHEATDODGESOUNDH__

#define CHEATDODGESOUNDFREQ 11025
#define CHEATDODGESOUNDLEN 4634

extern const unsigned char CheatDodgeSound[4634];

#endif /* __CHEATDODGESOUNDH__ */

/**************************************************************
 *
 *	CheatKOSound, 8 bit, 11025Hz,
 *	1 channel, 82304 bytes/channel
 *	Total Size: 1 * 82304 + 4 (header) = 82348 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatKOSound.wav
 *	Time-stamp: Fri Apr 06 22:40:23 2018
 *
 **************************************************************/

#ifndef __CHEATKOSOUNDH__
#define __CHEATKOSOUNDH__

#define CHEATKOSOUNDFREQ 11025
#define CHEATKOSOUNDLEN 82304

extern const unsigned char CheatKOSound[82304];

#endif /* __CHEATKOSOUNDH__ */

/**************************************************************
 *
 *	CheatPunchSound, 8 bit, 11025Hz,
 *	1 channel, 14885 bytes/channel
 *	Total Size: 1 * 14885 + 4 (header) = 14929 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatPunchSound.wav
 *	Time-stamp: Fri Apr 06 22:40:03 2018
 *
 **************************************************************/

#ifndef __CHEATPUNCHSOUNDH__
#define __CHEATPUNCHSOUNDH__

#define CHEATPUNCHSOUNDFREQ 11025
#define CHEATPUNCHSOUNDLEN 14885

extern const unsigned char CheatPunchSound[14885];

#endif /* __CHEATPUNCHSOUNDH__ */

/**************************************************************
 *
 *	SelectSound, 8 bit, 11025Hz,
 *	1 channel, 2523 bytes/channel
 *	Total Size: 1 * 2523 + 4 (header) = 2567 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/MenuSounds/Output/SelectSound.wav
 *	Time-stamp: Fri Apr 06 23:26:30 2018
 *
 **************************************************************/

#ifndef __SELECTSOUNDH__
#define __SELECTSOUNDH__

#define SELECTSOUNDFREQ 11025
#define SELECTSOUNDLEN 2523

extern const unsigned char SelectSound[2523];

#endif /* __SELECTSOUNDH__ */

/**************************************************************
 *
 *	StartSound, 8 bit, 11025Hz,
 *	1 channel, 5746 bytes/channel
 *	Total Size: 1 * 5746 + 4 (header) = 5790 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/MenuSounds/Output/StartSound.wav
 *	Time-stamp: Fri Apr 06 23:26:36 2018
 *
 **************************************************************/

#ifndef __STARTSOUNDH__
#define __STARTSOUNDH__

#define STARTSOUNDFREQ 11025
#define STARTSOUNDLEN 5746

extern const unsigned char StartSound[5746];

#endif /* __STARTSOUNDH__ */

/**************************************************************
 *
 *	EightCountSound, 8 bit, 11025Hz,
 *	1 channel, 12491 bytes/channel
 *	Total Size: 1 * 12491 + 4 (header) = 12535 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/EightCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:26 2018
 *
 **************************************************************/

#ifndef __EIGHTCOUNTSOUNDH__
#define __EIGHTCOUNTSOUNDH__

#define EIGHTCOUNTSOUNDFREQ 11025
#define EIGHTCOUNTSOUNDLEN 12491

extern const unsigned char EightCountSound[12491];

#endif /* __EIGHTCOUNTSOUNDH__ */

/**************************************************************
 *
 *	FiveCountSound, 8 bit, 11025Hz,
 *	1 channel, 8191 bytes/channel
 *	Total Size: 1 * 8191 + 4 (header) = 8235 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FiveCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:03 2018
 *
 **************************************************************/

#ifndef __FIVECOUNTSOUNDH__
#define __FIVECOUNTSOUNDH__

#define FIVECOUNTSOUNDFREQ 11025
#define FIVECOUNTSOUNDLEN 8191

extern const unsigned char FiveCountSound[8191];

#endif /* __FIVECOUNTSOUNDH__ */

/**************************************************************
 *
 *	FourCountSound, 8 bit, 11025Hz,
 *	1 channel, 8582 bytes/channel
 *	Total Size: 1 * 8582 + 4 (header) = 8626 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FourCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:47 2018
 *
 **************************************************************/

#ifndef __FOURCOUNTSOUNDH__
#define __FOURCOUNTSOUNDH__

#define FOURCOUNTSOUNDFREQ 11025
#define FOURCOUNTSOUNDLEN 8582

extern const unsigned char FourCountSound[8582];

#endif /* __FOURCOUNTSOUNDH__ */

/**************************************************************
 *
 *	KnockoutCountSound, 8 bit, 11025Hz,
 *	1 channel, 23383 bytes/channel
 *	Total Size: 1 * 23383 + 4 (header) = 23427 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/KnockoutCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:25 2018
 *
 **************************************************************/

#ifndef __KNOCKOUTCOUNTSOUNDH__
#define __KNOCKOUTCOUNTSOUNDH__

#define KNOCKOUTCOUNTSOUNDFREQ 11025
#define KNOCKOUTCOUNTSOUNDLEN 23383

extern const unsigned char KnockoutCountSound[23383];

#endif /* __KNOCKOUTCOUNTSOUNDH__ */

/**************************************************************
 *
 *	NineCountSound, 8 bit, 11025Hz,
 *	1 channel, 10240 bytes/channel
 *	Total Size: 1 * 10240 + 4 (header) = 10284 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/NineCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:56 2018
 *
 **************************************************************/

#ifndef __NINECOUNTSOUNDH__
#define __NINECOUNTSOUNDH__

#define NINECOUNTSOUNDFREQ 11025
#define NINECOUNTSOUNDLEN 10240

extern const unsigned char NineCountSound[10240];

#endif /* __NINECOUNTSOUNDH__ */

/**************************************************************
 *
 *	OneCountSound, 8 bit, 11025Hz,
 *	1 channel, 6613 bytes/channel
 *	Total Size: 1 * 6613 + 4 (header) = 6657 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/OneCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:24 2018
 *
 **************************************************************/

#ifndef __ONECOUNTSOUNDH__
#define __ONECOUNTSOUNDH__

#define ONECOUNTSOUNDFREQ 11025
#define ONECOUNTSOUNDLEN 6613

extern const unsigned char OneCountSound[6613];

#endif /* __ONECOUNTSOUNDH__ */

/**************************************************************
 *
 *	ReadyFightSound, 8 bit, 11025Hz,
 *	1 channel, 19456 bytes/channel
 *	Total Size: 1 * 19456 + 4 (header) = 19500 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ReadyFightSound.wav
 *	Time-stamp: Sat Apr 07 14:52:38 2018
 *
 **************************************************************/

#ifndef __READYFIGHTSOUNDH__
#define __READYFIGHTSOUNDH__

#define READYFIGHTSOUNDFREQ 11025
#define READYFIGHTSOUNDLEN 19456

extern const unsigned char ReadyFightSound[19456];

#endif /* __READYFIGHTSOUNDH__ */

/**************************************************************
 *
 *	SevenCountSound, 8 bit, 11025Hz,
 *	1 channel, 11448 bytes/channel
 *	Total Size: 1 * 11448 + 4 (header) = 11492 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SevenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:20 2018
 *
 **************************************************************/

#ifndef __SEVENCOUNTSOUNDH__
#define __SEVENCOUNTSOUNDH__

#define SEVENCOUNTSOUNDFREQ 11025
#define SEVENCOUNTSOUNDLEN 11448

extern const unsigned char SevenCountSound[11448];

#endif /* __SEVENCOUNTSOUNDH__ */

/**************************************************************
 *
 *	SixCountSound, 8 bit, 11025Hz,
 *	1 channel, 10405 bytes/channel
 *	Total Size: 1 * 10405 + 4 (header) = 10449 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SixCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:12 2018
 *
 **************************************************************/

#ifndef __SIXCOUNTSOUNDH__
#define __SIXCOUNTSOUNDH__

#define SIXCOUNTSOUNDFREQ 11025
#define SIXCOUNTSOUNDLEN 10405

extern const unsigned char SixCountSound[10405];

#endif /* __SIXCOUNTSOUNDH__ */

/**************************************************************
 *
 *	TenCountSound, 8 bit, 11025Hz,
 *	1 channel, 15382 bytes/channel
 *	Total Size: 1 * 15382 + 4 (header) = 15426 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:33 2018
 *
 **************************************************************/

#ifndef __TENCOUNTSOUNDH__
#define __TENCOUNTSOUNDH__

#define TENCOUNTSOUNDFREQ 11025
#define TENCOUNTSOUNDLEN 15382

extern const unsigned char TenCountSound[15382];

#endif /* __TENCOUNTSOUNDH__ */

/**************************************************************
 *
 *	ThreeCountSound, 8 bit, 11025Hz,
 *	1 channel, 8972 bytes/channel
 *	Total Size: 1 * 8972 + 4 (header) = 9016 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ThreeCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:35 2018
 *
 **************************************************************/

#ifndef __THREECOUNTSOUNDH__
#define __THREECOUNTSOUNDH__

#define THREECOUNTSOUNDFREQ 11025
#define THREECOUNTSOUNDLEN 8972

extern const unsigned char ThreeCountSound[8972];

#endif /* __THREECOUNTSOUNDH__ */

/**************************************************************
 *
 *	TwoCountSound, 8 bit, 11025Hz,
 *	1 channel, 8777 bytes/channel
 *	Total Size: 1 * 8777 + 4 (header) = 8821 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TwoCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:41 2018
 *
 **************************************************************/

#ifndef __TWOCOUNTSOUNDH__
#define __TWOCOUNTSOUNDH__

#define TWOCOUNTSOUNDFREQ 11025
#define TWOCOUNTSOUNDLEN 8777

extern const unsigned char TwoCountSound[8777];

#endif /* __TWOCOUNTSOUNDH__ */

/**************************************************************
 *
 *	CorruptionAudio1, 8 bit, 11025Hz,
 *	1 channel, 28672 bytes/channel
 *	Total Size: 1 * 28672 + 4 (header) = 28716 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio1.wav
 *	Time-stamp: Sun Apr 15 02:13:52 2018
 *
 **************************************************************/

#ifndef __CORRUPTIONAUDIO1H__
#define __CORRUPTIONAUDIO1H__

#define CORRUPTIONAUDIO1FREQ 11025
#define CORRUPTIONAUDIO1LEN 28672

extern const unsigned char CorruptionAudio1[28672];

#endif /* __CORRUPTIONAUDIO1H__ */

/**************************************************************
 *
 *	CorruptionAudio0, 8 bit, 11025Hz,
 *	1 channel, 88832 bytes/channel
 *	Total Size: 1 * 88832 + 4 (header) = 88876 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio0.wav
 *	Time-stamp: Sun Apr 15 02:13:50 2018
 *
 **************************************************************/

#ifndef __CORRUPTIONAUDIO0H__
#define __CORRUPTIONAUDIO0H__

#define CORRUPTIONAUDIO0FREQ 11025
#define CORRUPTIONAUDIO0LEN 88832

extern const unsigned char CorruptionAudio0[88832];

#endif /* __CORRUPTIONAUDIO0H__ */

/**************************************************************
 *
 *	CorruptionAudio2, 8 bit, 11025Hz,
 *	1 channel, 25703 bytes/channel
 *	Total Size: 1 * 25703 + 4 (header) = 25747 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio2.wav
 *	Time-stamp: Sun Apr 15 02:13:57 2018
 *
 **************************************************************/

#ifndef __CORRUPTIONAUDIO2H__
#define __CORRUPTIONAUDIO2H__

#define CORRUPTIONAUDIO2FREQ 11025
#define CORRUPTIONAUDIO2LEN 25703

extern const unsigned char CorruptionAudio2[25703];

#endif /* __CORRUPTIONAUDIO2H__ */

/**************************************************************
 *
 *	CorruptionAudio3, 8 bit, 11025Hz,
 *	1 channel, 30208 bytes/channel
 *	Total Size: 1 * 30208 + 4 (header) = 30252 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio3.wav
 *	Time-stamp: Sun Apr 15 02:14:00 2018
 *
 **************************************************************/

#ifndef __CORRUPTIONAUDIO3H__
#define __CORRUPTIONAUDIO3H__

#define CORRUPTIONAUDIO3FREQ 11025
#define CORRUPTIONAUDIO3LEN 30208

extern const unsigned char CorruptionAudio3[30208];

#endif /* __CORRUPTIONAUDIO3H__ */

/**************************************************************
 *
 *	RecordScratch, 8 bit, 11025Hz,
 *	1 channel, 5885 bytes/channel
 *	Total Size: 1 * 5885 + 4 (header) = 5929 bytes
 *
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/RecordScratch.wav
 *	Time-stamp: Sun Apr 15 02:48:50 2018
 *
 **************************************************************/

#ifndef __RECORDSCRATCHH__
#define __RECORDSCRATCHH__

#define RECORDSCRATCHFREQ 11025
#define RECORDSCRATCHLEN 5885

extern const unsigned char RecordScratch[5885];

#endif /* __RECORDSCRATCHH__ */
