
/**************************************************************
 *	
 *	TitleMusic2, 8 bit, 11025Hz,
 *	1 channel, 1709020 bytes/channel
 *	Total Size: 1 * 1709020 + 4 (header) = 1709064 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/TitleMusic2.wav
 *	Time-stamp: Fri Apr 06 19:51:18 2018
 *	
 **************************************************************/

#ifndef __TITLEMUSIC2H__
#define __TITLEMUSIC2H__

#define TITLEMUSIC2FREQ 11025
#define TITLEMUSIC2LEN 1709020

extern const unsigned char TitleMusic2[1709020];

#endif /* __TITLEMUSIC2H__ */
