
/**************************************************************
 *	
 *	TitleMusic4, 8 bit, 11025Hz,
 *	1 channel, 956736 bytes/channel
 *	Total Size: 1 * 956736 + 4 (header) = 956780 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/TitleMusic4.wav
 *	Time-stamp: Fri Apr 06 19:24:30 2018
 *	
 **************************************************************/

#ifndef __TITLEMUSIC4H__
#define __TITLEMUSIC4H__

#define TITLEMUSIC4FREQ 11025
#define TITLEMUSIC4LEN 956736

extern const unsigned char TitleMusic4[956736];

#endif /* __TITLEMUSIC4H__ */
