
/**************************************************************
 *	
 *	BlockSound, 8 bit, 11025Hz,
 *	1 channel, 5156 bytes/channel
 *	Total Size: 1 * 5156 + 4 (header) = 5200 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/BlockSound.wav
 *	Time-stamp: Fri Apr 06 20:58:39 2018
 *	
 **************************************************************/

#ifndef __BLOCKSOUNDH__
#define __BLOCKSOUNDH__

#define BLOCKSOUNDFREQ 11025
#define BLOCKSOUNDLEN 5156

extern const unsigned char BlockSound[5156];

#endif /* __BLOCKSOUNDH__ */
