
/**************************************************************
 *	
 *	ChampPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5366 bytes/channel
 *	Total Size: 1 * 5366 + 4 (header) = 5410 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound1.wav
 *	Time-stamp: Fri Apr 06 20:59:52 2018
 *	
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND1H__
#define __CHAMPPUNCHSOUND1H__

#define CHAMPPUNCHSOUND1FREQ 11025
#define CHAMPPUNCHSOUND1LEN 5366

extern const unsigned char ChampPunchSound1[5366];

#endif /* __CHAMPPUNCHSOUND1H__ */
