
/**************************************************************
 *	
 *	ChampWindSound, 8 bit, 11025Hz,
 *	1 channel, 2958 bytes/channel
 *	Total Size: 1 * 2958 + 4 (header) = 3002 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampWindSound.wav
 *	Time-stamp: Fri Apr 06 20:59:58 2018
 *	
 **************************************************************/

#ifndef __CHAMPWINDSOUNDH__
#define __CHAMPWINDSOUNDH__

#define CHAMPWINDSOUNDFREQ 11025
#define CHAMPWINDSOUNDLEN 2958

extern const unsigned char ChampWindSound[2958];

#endif /* __CHAMPWINDSOUNDH__ */
