
/**************************************************************
 *	
 *	ChampFeintSound, 8 bit, 11025Hz,
 *	1 channel, 5170 bytes/channel
 *	Total Size: 1 * 5170 + 4 (header) = 5214 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampFeintSound.wav
 *	Time-stamp: Fri Apr 06 20:59:32 2018
 *	
 **************************************************************/

#ifndef __CHAMPFEINTSOUNDH__
#define __CHAMPFEINTSOUNDH__

#define CHAMPFEINTSOUNDFREQ 11025
#define CHAMPFEINTSOUNDLEN 5170

extern const unsigned char ChampFeintSound[5170];

#endif /* __CHAMPFEINTSOUNDH__ */
