
/**************************************************************
 *	
 *	ChampPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 6971 bytes/channel
 *	Total Size: 1 * 6971 + 4 (header) = 7015 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound0.wav
 *	Time-stamp: Fri Apr 06 20:59:43 2018
 *	
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND0H__
#define __CHAMPPUNCHSOUND0H__

#define CHAMPPUNCHSOUND0FREQ 11025
#define CHAMPPUNCHSOUND0LEN 6971

extern const unsigned char ChampPunchSound0[6971];

#endif /* __CHAMPPUNCHSOUND0H__ */
