
/**************************************************************
 *	
 *	KOSound, 8 bit, 11025Hz,
 *	1 channel, 16645 bytes/channel
 *	Total Size: 1 * 16645 + 4 (header) = 16689 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/KOSound.wav
 *	Time-stamp: Fri Apr 06 21:00:05 2018
 *	
 **************************************************************/

#ifndef __KOSOUNDH__
#define __KOSOUNDH__

#define KOSOUNDFREQ 11025
#define KOSOUNDLEN 16645

extern const unsigned char KOSound[16645];

#endif /* __KOSOUNDH__ */
