
/**************************************************************
 *	
 *	BlockSound, 8 bit, 11025Hz,
 *	1 channel, 5156 bytes/channel
 *	Total Size: 1 * 5156 + 4 (header) = 5200 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/BlockSound.wav
 *	Time-stamp: Fri Apr 06 20:58:39 2018
 *	
 **************************************************************/

#ifndef __BLOCKSOUNDH__
#define __BLOCKSOUNDH__

#define BLOCKSOUNDFREQ 11025
#define BLOCKSOUNDLEN 5156

extern const unsigned char BlockSound[5156];

#endif /* __BLOCKSOUNDH__ */

/**************************************************************
 *	
 *	ChampFeintSound, 8 bit, 11025Hz,
 *	1 channel, 5170 bytes/channel
 *	Total Size: 1 * 5170 + 4 (header) = 5214 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampFeintSound.wav
 *	Time-stamp: Fri Apr 06 20:59:32 2018
 *	
 **************************************************************/

#ifndef __CHAMPFEINTSOUNDH__
#define __CHAMPFEINTSOUNDH__

#define CHAMPFEINTSOUNDFREQ 11025
#define CHAMPFEINTSOUNDLEN 5170

extern const unsigned char ChampFeintSound[5170];

#endif /* __CHAMPFEINTSOUNDH__ */

/**************************************************************
 *	
 *	ChampPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 6971 bytes/channel
 *	Total Size: 1 * 6971 + 4 (header) = 7015 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound0.wav
 *	Time-stamp: Fri Apr 06 20:59:43 2018
 *	
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND0H__
#define __CHAMPPUNCHSOUND0H__

#define CHAMPPUNCHSOUND0FREQ 11025
#define CHAMPPUNCHSOUND0LEN 6971

extern const unsigned char ChampPunchSound0[6971];

#endif /* __CHAMPPUNCHSOUND0H__ */

/**************************************************************
 *	
 *	ChampPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5366 bytes/channel
 *	Total Size: 1 * 5366 + 4 (header) = 5410 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampPunchSound1.wav
 *	Time-stamp: Fri Apr 06 20:59:52 2018
 *	
 **************************************************************/

#ifndef __CHAMPPUNCHSOUND1H__
#define __CHAMPPUNCHSOUND1H__

#define CHAMPPUNCHSOUND1FREQ 11025
#define CHAMPPUNCHSOUND1LEN 5366

extern const unsigned char ChampPunchSound1[5366];

#endif /* __CHAMPPUNCHSOUND1H__ */

/**************************************************************
 *	
 *	ChampWindSound, 8 bit, 11025Hz,
 *	1 channel, 2958 bytes/channel
 *	Total Size: 1 * 2958 + 4 (header) = 3002 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/ChampWindSound.wav
 *	Time-stamp: Fri Apr 06 20:59:58 2018
 *	
 **************************************************************/

#ifndef __CHAMPWINDSOUNDH__
#define __CHAMPWINDSOUNDH__

#define CHAMPWINDSOUNDFREQ 11025
#define CHAMPWINDSOUNDLEN 2958

extern const unsigned char ChampWindSound[2958];

#endif /* __CHAMPWINDSOUNDH__ */

/**************************************************************
 *	
 *	KOSound, 8 bit, 11025Hz,
 *	1 channel, 16645 bytes/channel
 *	Total Size: 1 * 16645 + 4 (header) = 16689 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/KOSound.wav
 *	Time-stamp: Fri Apr 06 21:00:05 2018
 *	
 **************************************************************/

#ifndef __KOSOUNDH__
#define __KOSOUNDH__

#define KOSOUNDFREQ 11025
#define KOSOUNDLEN 16645

extern const unsigned char KOSound[16645];

#endif /* __KOSOUNDH__ */

/**************************************************************
 *	
 *	PlayerDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 3511 bytes/channel
 *	Total Size: 1 * 3511 + 4 (header) = 3555 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerDodgeSound.wav
 *	Time-stamp: Fri Apr 06 21:00:28 2018
 *	
 **************************************************************/

#ifndef __PLAYERDODGESOUNDH__
#define __PLAYERDODGESOUNDH__

#define PLAYERDODGESOUNDFREQ 11025
#define PLAYERDODGESOUNDLEN 3511

extern const unsigned char PlayerDodgeSound[3511];

#endif /* __PLAYERDODGESOUNDH__ */

/**************************************************************
 *	
 *	PlayerPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 4984 bytes/channel
 *	Total Size: 1 * 4984 + 4 (header) = 5028 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound0.wav
 *	Time-stamp: Fri Apr 06 21:00:12 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND0H__
#define __PLAYERPUNCHSOUND0H__

#define PLAYERPUNCHSOUND0FREQ 11025
#define PLAYERPUNCHSOUND0LEN 4984

extern const unsigned char PlayerPunchSound0[4984];

#endif /* __PLAYERPUNCHSOUND0H__ */

/**************************************************************
 *	
 *	PlayerPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5151 bytes/channel
 *	Total Size: 1 * 5151 + 4 (header) = 5195 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound1.wav
 *	Time-stamp: Fri Apr 06 21:00:20 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND1H__
#define __PLAYERPUNCHSOUND1H__

#define PLAYERPUNCHSOUND1FREQ 11025
#define PLAYERPUNCHSOUND1LEN 5151

extern const unsigned char PlayerPunchSound1[5151];

#endif /* __PLAYERPUNCHSOUND1H__ */

/**************************************************************
 *	
 *	PlayerPunchSound2, 8 bit, 11025Hz,
 *	1 channel, 7876 bytes/channel
 *	Total Size: 1 * 7876 + 4 (header) = 7920 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound2.wav
 *	Time-stamp: Fri Apr 06 21:00:33 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND2H__
#define __PLAYERPUNCHSOUND2H__

#define PLAYERPUNCHSOUND2FREQ 11025
#define PLAYERPUNCHSOUND2LEN 7876

extern const unsigned char PlayerPunchSound2[7876];

#endif /* __PLAYERPUNCHSOUND2H__ */
