
/**************************************************************
 *	
 *	PlayerPunchSound1, 8 bit, 11025Hz,
 *	1 channel, 5151 bytes/channel
 *	Total Size: 1 * 5151 + 4 (header) = 5195 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound1.wav
 *	Time-stamp: Fri Apr 06 21:00:20 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND1H__
#define __PLAYERPUNCHSOUND1H__

#define PLAYERPUNCHSOUND1FREQ 11025
#define PLAYERPUNCHSOUND1LEN 5151

extern const unsigned char PlayerPunchSound1[5151];

#endif /* __PLAYERPUNCHSOUND1H__ */
