
/**************************************************************
 *	
 *	PlayerPunchSound2, 8 bit, 11025Hz,
 *	1 channel, 7876 bytes/channel
 *	Total Size: 1 * 7876 + 4 (header) = 7920 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound2.wav
 *	Time-stamp: Fri Apr 06 21:00:33 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND2H__
#define __PLAYERPUNCHSOUND2H__

#define PLAYERPUNCHSOUND2FREQ 11025
#define PLAYERPUNCHSOUND2LEN 7876

extern const unsigned char PlayerPunchSound2[7876];

#endif /* __PLAYERPUNCHSOUND2H__ */
