
/**************************************************************
 *	
 *	PlayerPunchSound0, 8 bit, 11025Hz,
 *	1 channel, 4984 bytes/channel
 *	Total Size: 1 * 4984 + 4 (header) = 5028 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerPunchSound0.wav
 *	Time-stamp: Fri Apr 06 21:00:12 2018
 *	
 **************************************************************/

#ifndef __PLAYERPUNCHSOUND0H__
#define __PLAYERPUNCHSOUND0H__

#define PLAYERPUNCHSOUND0FREQ 11025
#define PLAYERPUNCHSOUND0LEN 4984

extern const unsigned char PlayerPunchSound0[4984];

#endif /* __PLAYERPUNCHSOUND0H__ */
