
/**************************************************************
 *	
 *	PlayerDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 3511 bytes/channel
 *	Total Size: 1 * 3511 + 4 (header) = 3555 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/PlayerDodgeSound.wav
 *	Time-stamp: Fri Apr 06 21:00:28 2018
 *	
 **************************************************************/

#ifndef __PLAYERDODGESOUNDH__
#define __PLAYERDODGESOUNDH__

#define PLAYERDODGESOUNDFREQ 11025
#define PLAYERDODGESOUNDLEN 3511

extern const unsigned char PlayerDodgeSound[3511];

#endif /* __PLAYERDODGESOUNDH__ */
