
/**************************************************************
 *	
 *	AudienceSounds, 8 bit, 11025Hz,
 *	1 channel, 60458 bytes/channel
 *	Total Size: 1 * 60458 + 4 (header) = 60502 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/AudienceSounds.wav
 *	Time-stamp: Sat Apr 07 15:50:59 2018
 *	
 **************************************************************/

#ifndef __AUDIENCESOUNDSH__
#define __AUDIENCESOUNDSH__

#define AUDIENCESOUNDSFREQ 11025
#define AUDIENCESOUNDSLEN 60458

extern const unsigned char AudienceSounds[60458];

#endif /* __AUDIENCESOUNDSH__ */
