
/**************************************************************
 *	
 *	ChampKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151883 bytes/channel
 *	Total Size: 1 * 151883 + 4 (header) = 151927 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/ChampKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:23 2018
 *	
 **************************************************************/

#ifndef __CHAMPKNOCKDOWNMUSICH__
#define __CHAMPKNOCKDOWNMUSICH__

#define CHAMPKNOCKDOWNMUSICFREQ 11025
#define CHAMPKNOCKDOWNMUSICLEN 151883

extern const unsigned char ChampKnockDownMusic[151883];

#endif /* __CHAMPKNOCKDOWNMUSICH__ */
