
/**************************************************************
 *	
 *	MatchFightMusic, 8 bit, 11025Hz,
 *	1 channel, 685237 bytes/channel
 *	Total Size: 1 * 685237 + 4 (header) = 685281 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/MatchFightMusic.wav
 *	Time-stamp: Sat Apr 07 15:50:52 2018
 *	
 **************************************************************/

#ifndef __MATCHFIGHTMUSICH__
#define __MATCHFIGHTMUSICH__

#define MATCHFIGHTMUSICFREQ 11025
#define MATCHFIGHTMUSICLEN 685237

extern const unsigned char MatchFightMusic[685237];

#endif /* __MATCHFIGHTMUSICH__ */
