
/**************************************************************
 *	
 *	AudienceSounds, 8 bit, 11025Hz,
 *	1 channel, 60458 bytes/channel
 *	Total Size: 1 * 60458 + 4 (header) = 60502 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/AudienceSounds.wav
 *	Time-stamp: Sat Apr 07 15:50:59 2018
 *	
 **************************************************************/

#ifndef __AUDIENCESOUNDSH__
#define __AUDIENCESOUNDSH__

#define AUDIENCESOUNDSFREQ 11025
#define AUDIENCESOUNDSLEN 60458

extern const unsigned char AudienceSounds[60458];

#endif /* __AUDIENCESOUNDSH__ */

/**************************************************************
 *	
 *	ChampKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151883 bytes/channel
 *	Total Size: 1 * 151883 + 4 (header) = 151927 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/ChampKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:23 2018
 *	
 **************************************************************/

#ifndef __CHAMPKNOCKDOWNMUSICH__
#define __CHAMPKNOCKDOWNMUSICH__

#define CHAMPKNOCKDOWNMUSICFREQ 11025
#define CHAMPKNOCKDOWNMUSICLEN 151883

extern const unsigned char ChampKnockDownMusic[151883];

#endif /* __CHAMPKNOCKDOWNMUSICH__ */

/**************************************************************
 *	
 *	MatchFightMusic, 8 bit, 11025Hz,
 *	1 channel, 685237 bytes/channel
 *	Total Size: 1 * 685237 + 4 (header) = 685281 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/MatchFightMusic.wav
 *	Time-stamp: Sat Apr 07 15:50:52 2018
 *	
 **************************************************************/

#ifndef __MATCHFIGHTMUSICH__
#define __MATCHFIGHTMUSICH__

#define MATCHFIGHTMUSICFREQ 11025
#define MATCHFIGHTMUSICLEN 685237

extern const unsigned char MatchFightMusic[685237];

#endif /* __MATCHFIGHTMUSICH__ */

/**************************************************************
 *	
 *	PlayerKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151488 bytes/channel
 *	Total Size: 1 * 151488 + 4 (header) = 151532 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/PlayerKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:07 2018
 *	
 **************************************************************/

#ifndef __PLAYERKNOCKDOWNMUSICH__
#define __PLAYERKNOCKDOWNMUSICH__

#define PLAYERKNOCKDOWNMUSICFREQ 11025
#define PLAYERKNOCKDOWNMUSICLEN 151488

extern const unsigned char PlayerKnockDownMusic[151488];

#endif /* __PLAYERKNOCKDOWNMUSICH__ */

/**************************************************************
 *	
 *	UltraFightMusic, 8 bit, 11025Hz,
 *	1 channel, 1167938 bytes/channel
 *	Total Size: 1 * 1167938 + 4 (header) = 1167982 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/UltraFightMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:12 2018
 *	
 **************************************************************/

#ifndef __ULTRAFIGHTMUSICH__
#define __ULTRAFIGHTMUSICH__

#define ULTRAFIGHTMUSICFREQ 11025
#define ULTRAFIGHTMUSICLEN 1167938

extern const unsigned char UltraFightMusic[1167938];

#endif /* __ULTRAFIGHTMUSICH__ */
