
/**************************************************************
 *	
 *	PlayerKnockDownMusic, 8 bit, 11025Hz,
 *	1 channel, 151488 bytes/channel
 *	Total Size: 1 * 151488 + 4 (header) = 151532 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/PlayerKnockDownMusic.wav
 *	Time-stamp: Sat Apr 07 15:51:07 2018
 *	
 **************************************************************/

#ifndef __PLAYERKNOCKDOWNMUSICH__
#define __PLAYERKNOCKDOWNMUSICH__

#define PLAYERKNOCKDOWNMUSICFREQ 11025
#define PLAYERKNOCKDOWNMUSICLEN 151488

extern const unsigned char PlayerKnockDownMusic[151488];

#endif /* __PLAYERKNOCKDOWNMUSICH__ */
