
/**************************************************************
 *	
 *	UltraFightMusic, 8 bit, 11025Hz,
 *	1 channel, 1167938 bytes/channel
 *	Total Size: 1 * 1167938 + 4 (header) = 1167982 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/UltraFightMusic.wav
 *	Time-stamp: Sat Apr 07 16:11:20 2018
 *	
 **************************************************************/

#ifndef __ULTRAFIGHTMUSICH__
#define __ULTRAFIGHTMUSICH__

#define ULTRAFIGHTMUSICFREQ 11025
#define ULTRAFIGHTMUSICLEN 1167938

extern const unsigned char UltraFightMusic[1167938];

#endif /* __ULTRAFIGHTMUSICH__ */
