
/**************************************************************
 *	
 *	CheatKOSound, 8 bit, 11025Hz,
 *	1 channel, 82304 bytes/channel
 *	Total Size: 1 * 82304 + 4 (header) = 82348 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatKOSound.wav
 *	Time-stamp: Fri Apr 06 22:40:23 2018
 *	
 **************************************************************/

#ifndef __CHEATKOSOUNDH__
#define __CHEATKOSOUNDH__

#define CHEATKOSOUNDFREQ 11025
#define CHEATKOSOUNDLEN 82304

extern const unsigned char CheatKOSound[82304];

#endif /* __CHEATKOSOUNDH__ */
