
/**************************************************************
 *	
 *	CheatAura, 8 bit, 11025Hz,
 *	1 channel, 63489 bytes/channel
 *	Total Size: 1 * 63489 + 4 (header) = 63533 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatAura.wav
 *	Time-stamp: Fri Apr 06 22:40:18 2018
 *	
 **************************************************************/

#ifndef __CHEATAURAH__
#define __CHEATAURAH__

#define CHEATAURAFREQ 11025
#define CHEATAURALEN 63489

extern const unsigned char CheatAura[63489];

#endif /* __CHEATAURAH__ */
