
/**************************************************************
 *	
 *	CheatPunchSound, 8 bit, 11025Hz,
 *	1 channel, 14885 bytes/channel
 *	Total Size: 1 * 14885 + 4 (header) = 14929 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatPunchSound.wav
 *	Time-stamp: Fri Apr 06 22:40:03 2018
 *	
 **************************************************************/

#ifndef __CHEATPUNCHSOUNDH__
#define __CHEATPUNCHSOUNDH__

#define CHEATPUNCHSOUNDFREQ 11025
#define CHEATPUNCHSOUNDLEN 14885

extern const unsigned char CheatPunchSound[14885];

#endif /* __CHEATPUNCHSOUNDH__ */
