
/**************************************************************
 *	
 *	CheatDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 4634 bytes/channel
 *	Total Size: 1 * 4634 + 4 (header) = 4678 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatDodgeSound.wav
 *	Time-stamp: Fri Apr 06 22:40:09 2018
 *	
 **************************************************************/

#ifndef __CHEATDODGESOUNDH__
#define __CHEATDODGESOUNDH__

#define CHEATDODGESOUNDFREQ 11025
#define CHEATDODGESOUNDLEN 4634

extern const unsigned char CheatDodgeSound[4634];

#endif /* __CHEATDODGESOUNDH__ */
