
/**************************************************************
 *	
 *	CheatBlockSound, 8 bit, 11025Hz,
 *	1 channel, 2177 bytes/channel
 *	Total Size: 1 * 2177 + 4 (header) = 2221 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatBlockSound.wav
 *	Time-stamp: Fri Apr 06 22:39:55 2018
 *	
 **************************************************************/

#ifndef __CHEATBLOCKSOUNDH__
#define __CHEATBLOCKSOUNDH__

#define CHEATBLOCKSOUNDFREQ 11025
#define CHEATBLOCKSOUNDLEN 2177

extern const unsigned char CheatBlockSound[2177];

#endif /* __CHEATBLOCKSOUNDH__ */
