
/**************************************************************
 *	
 *	CheatAura, 8 bit, 11025Hz,
 *	1 channel, 63489 bytes/channel
 *	Total Size: 1 * 63489 + 4 (header) = 63533 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatAura.wav
 *	Time-stamp: Fri Apr 06 22:40:18 2018
 *	
 **************************************************************/

#ifndef __CHEATAURAH__
#define __CHEATAURAH__

#define CHEATAURAFREQ 11025
#define CHEATAURALEN 63489

extern const unsigned char CheatAura[63489];

#endif /* __CHEATAURAH__ */

/**************************************************************
 *	
 *	CheatBlockSound, 8 bit, 11025Hz,
 *	1 channel, 2177 bytes/channel
 *	Total Size: 1 * 2177 + 4 (header) = 2221 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatBlockSound.wav
 *	Time-stamp: Fri Apr 06 22:39:55 2018
 *	
 **************************************************************/

#ifndef __CHEATBLOCKSOUNDH__
#define __CHEATBLOCKSOUNDH__

#define CHEATBLOCKSOUNDFREQ 11025
#define CHEATBLOCKSOUNDLEN 2177

extern const unsigned char CheatBlockSound[2177];

#endif /* __CHEATBLOCKSOUNDH__ */

/**************************************************************
 *	
 *	CheatDodgeSound, 8 bit, 11025Hz,
 *	1 channel, 4634 bytes/channel
 *	Total Size: 1 * 4634 + 4 (header) = 4678 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatDodgeSound.wav
 *	Time-stamp: Fri Apr 06 22:40:09 2018
 *	
 **************************************************************/

#ifndef __CHEATDODGESOUNDH__
#define __CHEATDODGESOUNDH__

#define CHEATDODGESOUNDFREQ 11025
#define CHEATDODGESOUNDLEN 4634

extern const unsigned char CheatDodgeSound[4634];

#endif /* __CHEATDODGESOUNDH__ */

/**************************************************************
 *	
 *	CheatKOSound, 8 bit, 11025Hz,
 *	1 channel, 82304 bytes/channel
 *	Total Size: 1 * 82304 + 4 (header) = 82348 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatKOSound.wav
 *	Time-stamp: Fri Apr 06 22:40:23 2018
 *	
 **************************************************************/

#ifndef __CHEATKOSOUNDH__
#define __CHEATKOSOUNDH__

#define CHEATKOSOUNDFREQ 11025
#define CHEATKOSOUNDLEN 82304

extern const unsigned char CheatKOSound[82304];

#endif /* __CHEATKOSOUNDH__ */

/**************************************************************
 *	
 *	CheatPunchSound, 8 bit, 11025Hz,
 *	1 channel, 14885 bytes/channel
 *	Total Size: 1 * 14885 + 4 (header) = 14929 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Output/SuperCheat/Output/CheatPunchSound.wav
 *	Time-stamp: Fri Apr 06 22:40:03 2018
 *	
 **************************************************************/

#ifndef __CHEATPUNCHSOUNDH__
#define __CHEATPUNCHSOUNDH__

#define CHEATPUNCHSOUNDFREQ 11025
#define CHEATPUNCHSOUNDLEN 14885

extern const unsigned char CheatPunchSound[14885];

#endif /* __CHEATPUNCHSOUNDH__ */
