
/**************************************************************
 *	
 *	EightCountSound, 8 bit, 11025Hz,
 *	1 channel, 12491 bytes/channel
 *	Total Size: 1 * 12491 + 4 (header) = 12535 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/EightCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:26 2018
 *	
 **************************************************************/

#ifndef __EIGHTCOUNTSOUNDH__
#define __EIGHTCOUNTSOUNDH__

#define EIGHTCOUNTSOUNDFREQ 11025
#define EIGHTCOUNTSOUNDLEN 12491

extern const unsigned char EightCountSound[12491];

#endif /* __EIGHTCOUNTSOUNDH__ */
