
/**************************************************************
 *	
 *	FiveCountSound, 8 bit, 11025Hz,
 *	1 channel, 8191 bytes/channel
 *	Total Size: 1 * 8191 + 4 (header) = 8235 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FiveCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:03 2018
 *	
 **************************************************************/

#ifndef __FIVECOUNTSOUNDH__
#define __FIVECOUNTSOUNDH__

#define FIVECOUNTSOUNDFREQ 11025
#define FIVECOUNTSOUNDLEN 8191

extern const unsigned char FiveCountSound[8191];

#endif /* __FIVECOUNTSOUNDH__ */
