
/**************************************************************
 *	
 *	FourCountSound, 8 bit, 11025Hz,
 *	1 channel, 8582 bytes/channel
 *	Total Size: 1 * 8582 + 4 (header) = 8626 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FourCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:47 2018
 *	
 **************************************************************/

#ifndef __FOURCOUNTSOUNDH__
#define __FOURCOUNTSOUNDH__

#define FOURCOUNTSOUNDFREQ 11025
#define FOURCOUNTSOUNDLEN 8582

extern const unsigned char FourCountSound[8582];

#endif /* __FOURCOUNTSOUNDH__ */
