
/**************************************************************
 *	
 *	KnockoutCountSound, 8 bit, 11025Hz,
 *	1 channel, 23383 bytes/channel
 *	Total Size: 1 * 23383 + 4 (header) = 23427 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/KnockoutCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:25 2018
 *	
 **************************************************************/

#ifndef __KNOCKOUTCOUNTSOUNDH__
#define __KNOCKOUTCOUNTSOUNDH__

#define KNOCKOUTCOUNTSOUNDFREQ 11025
#define KNOCKOUTCOUNTSOUNDLEN 23383

extern const unsigned char KnockoutCountSound[23383];

#endif /* __KNOCKOUTCOUNTSOUNDH__ */
