
/**************************************************************
 *	
 *	NineCountSound, 8 bit, 11025Hz,
 *	1 channel, 10240 bytes/channel
 *	Total Size: 1 * 10240 + 4 (header) = 10284 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/NineCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:56 2018
 *	
 **************************************************************/

#ifndef __NINECOUNTSOUNDH__
#define __NINECOUNTSOUNDH__

#define NINECOUNTSOUNDFREQ 11025
#define NINECOUNTSOUNDLEN 10240

extern const unsigned char NineCountSound[10240];

#endif /* __NINECOUNTSOUNDH__ */
