
/**************************************************************
 *	
 *	OneCountSound, 8 bit, 11025Hz,
 *	1 channel, 6613 bytes/channel
 *	Total Size: 1 * 6613 + 4 (header) = 6657 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/OneCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:24 2018
 *	
 **************************************************************/

#ifndef __ONECOUNTSOUNDH__
#define __ONECOUNTSOUNDH__

#define ONECOUNTSOUNDFREQ 11025
#define ONECOUNTSOUNDLEN 6613

extern const unsigned char OneCountSound[6613];

#endif /* __ONECOUNTSOUNDH__ */
