
/**************************************************************
 *	
 *	EightCountSound, 8 bit, 11025Hz,
 *	1 channel, 12491 bytes/channel
 *	Total Size: 1 * 12491 + 4 (header) = 12535 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/EightCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:26 2018
 *	
 **************************************************************/

#ifndef __EIGHTCOUNTSOUNDH__
#define __EIGHTCOUNTSOUNDH__

#define EIGHTCOUNTSOUNDFREQ 11025
#define EIGHTCOUNTSOUNDLEN 12491

extern const unsigned char EightCountSound[12491];

#endif /* __EIGHTCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	FiveCountSound, 8 bit, 11025Hz,
 *	1 channel, 8191 bytes/channel
 *	Total Size: 1 * 8191 + 4 (header) = 8235 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FiveCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:03 2018
 *	
 **************************************************************/

#ifndef __FIVECOUNTSOUNDH__
#define __FIVECOUNTSOUNDH__

#define FIVECOUNTSOUNDFREQ 11025
#define FIVECOUNTSOUNDLEN 8191

extern const unsigned char FiveCountSound[8191];

#endif /* __FIVECOUNTSOUNDH__ */

/**************************************************************
 *	
 *	FourCountSound, 8 bit, 11025Hz,
 *	1 channel, 8582 bytes/channel
 *	Total Size: 1 * 8582 + 4 (header) = 8626 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/FourCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:47 2018
 *	
 **************************************************************/

#ifndef __FOURCOUNTSOUNDH__
#define __FOURCOUNTSOUNDH__

#define FOURCOUNTSOUNDFREQ 11025
#define FOURCOUNTSOUNDLEN 8582

extern const unsigned char FourCountSound[8582];

#endif /* __FOURCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	KnockoutCountSound, 8 bit, 11025Hz,
 *	1 channel, 23383 bytes/channel
 *	Total Size: 1 * 23383 + 4 (header) = 23427 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/KnockoutCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:25 2018
 *	
 **************************************************************/

#ifndef __KNOCKOUTCOUNTSOUNDH__
#define __KNOCKOUTCOUNTSOUNDH__

#define KNOCKOUTCOUNTSOUNDFREQ 11025
#define KNOCKOUTCOUNTSOUNDLEN 23383

extern const unsigned char KnockoutCountSound[23383];

#endif /* __KNOCKOUTCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	NineCountSound, 8 bit, 11025Hz,
 *	1 channel, 10240 bytes/channel
 *	Total Size: 1 * 10240 + 4 (header) = 10284 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/NineCountSound.wav
 *	Time-stamp: Sat Apr 07 14:52:56 2018
 *	
 **************************************************************/

#ifndef __NINECOUNTSOUNDH__
#define __NINECOUNTSOUNDH__

#define NINECOUNTSOUNDFREQ 11025
#define NINECOUNTSOUNDLEN 10240

extern const unsigned char NineCountSound[10240];

#endif /* __NINECOUNTSOUNDH__ */

/**************************************************************
 *	
 *	OneCountSound, 8 bit, 11025Hz,
 *	1 channel, 6613 bytes/channel
 *	Total Size: 1 * 6613 + 4 (header) = 6657 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/OneCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:24 2018
 *	
 **************************************************************/

#ifndef __ONECOUNTSOUNDH__
#define __ONECOUNTSOUNDH__

#define ONECOUNTSOUNDFREQ 11025
#define ONECOUNTSOUNDLEN 6613

extern const unsigned char OneCountSound[6613];

#endif /* __ONECOUNTSOUNDH__ */

/**************************************************************
 *	
 *	ReadyFightSound, 8 bit, 11025Hz,
 *	1 channel, 19456 bytes/channel
 *	Total Size: 1 * 19456 + 4 (header) = 19500 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ReadyFightSound.wav
 *	Time-stamp: Sat Apr 07 14:52:38 2018
 *	
 **************************************************************/

#ifndef __READYFIGHTSOUNDH__
#define __READYFIGHTSOUNDH__

#define READYFIGHTSOUNDFREQ 11025
#define READYFIGHTSOUNDLEN 19456

extern const unsigned char ReadyFightSound[19456];

#endif /* __READYFIGHTSOUNDH__ */

/**************************************************************
 *	
 *	SevenCountSound, 8 bit, 11025Hz,
 *	1 channel, 11448 bytes/channel
 *	Total Size: 1 * 11448 + 4 (header) = 11492 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SevenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:20 2018
 *	
 **************************************************************/

#ifndef __SEVENCOUNTSOUNDH__
#define __SEVENCOUNTSOUNDH__

#define SEVENCOUNTSOUNDFREQ 11025
#define SEVENCOUNTSOUNDLEN 11448

extern const unsigned char SevenCountSound[11448];

#endif /* __SEVENCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	SixCountSound, 8 bit, 11025Hz,
 *	1 channel, 10405 bytes/channel
 *	Total Size: 1 * 10405 + 4 (header) = 10449 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SixCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:12 2018
 *	
 **************************************************************/

#ifndef __SIXCOUNTSOUNDH__
#define __SIXCOUNTSOUNDH__

#define SIXCOUNTSOUNDFREQ 11025
#define SIXCOUNTSOUNDLEN 10405

extern const unsigned char SixCountSound[10405];

#endif /* __SIXCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	TenCountSound, 8 bit, 11025Hz,
 *	1 channel, 15382 bytes/channel
 *	Total Size: 1 * 15382 + 4 (header) = 15426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:33 2018
 *	
 **************************************************************/

#ifndef __TENCOUNTSOUNDH__
#define __TENCOUNTSOUNDH__

#define TENCOUNTSOUNDFREQ 11025
#define TENCOUNTSOUNDLEN 15382

extern const unsigned char TenCountSound[15382];

#endif /* __TENCOUNTSOUNDH__ */

/**************************************************************
 *	
 *	ThreeCountSound, 8 bit, 11025Hz,
 *	1 channel, 8972 bytes/channel
 *	Total Size: 1 * 8972 + 4 (header) = 9016 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ThreeCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:35 2018
 *	
 **************************************************************/

#ifndef __THREECOUNTSOUNDH__
#define __THREECOUNTSOUNDH__

#define THREECOUNTSOUNDFREQ 11025
#define THREECOUNTSOUNDLEN 8972

extern const unsigned char ThreeCountSound[8972];

#endif /* __THREECOUNTSOUNDH__ */

/**************************************************************
 *	
 *	TwoCountSound, 8 bit, 11025Hz,
 *	1 channel, 8777 bytes/channel
 *	Total Size: 1 * 8777 + 4 (header) = 8821 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TwoCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:41 2018
 *	
 **************************************************************/

#ifndef __TWOCOUNTSOUNDH__
#define __TWOCOUNTSOUNDH__

#define TWOCOUNTSOUNDFREQ 11025
#define TWOCOUNTSOUNDLEN 8777

extern const unsigned char TwoCountSound[8777];

#endif /* __TWOCOUNTSOUNDH__ */
