
/**************************************************************
 *	
 *	ReadyFightSound, 8 bit, 11025Hz,
 *	1 channel, 19456 bytes/channel
 *	Total Size: 1 * 19456 + 4 (header) = 19500 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ReadyFightSound.wav
 *	Time-stamp: Sat Apr 07 14:52:38 2018
 *	
 **************************************************************/

#ifndef __READYFIGHTSOUNDH__
#define __READYFIGHTSOUNDH__

#define READYFIGHTSOUNDFREQ 11025
#define READYFIGHTSOUNDLEN 19456

extern const unsigned char ReadyFightSound[19456];

#endif /* __READYFIGHTSOUNDH__ */
