
/**************************************************************
 *	
 *	SevenCountSound, 8 bit, 11025Hz,
 *	1 channel, 11448 bytes/channel
 *	Total Size: 1 * 11448 + 4 (header) = 11492 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SevenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:20 2018
 *	
 **************************************************************/

#ifndef __SEVENCOUNTSOUNDH__
#define __SEVENCOUNTSOUNDH__

#define SEVENCOUNTSOUNDFREQ 11025
#define SEVENCOUNTSOUNDLEN 11448

extern const unsigned char SevenCountSound[11448];

#endif /* __SEVENCOUNTSOUNDH__ */
