
/**************************************************************
 *	
 *	SixCountSound, 8 bit, 11025Hz,
 *	1 channel, 10405 bytes/channel
 *	Total Size: 1 * 10405 + 4 (header) = 10449 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/SixCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:12 2018
 *	
 **************************************************************/

#ifndef __SIXCOUNTSOUNDH__
#define __SIXCOUNTSOUNDH__

#define SIXCOUNTSOUNDFREQ 11025
#define SIXCOUNTSOUNDLEN 10405

extern const unsigned char SixCountSound[10405];

#endif /* __SIXCOUNTSOUNDH__ */
