
/**************************************************************
 *	
 *	TenCountSound, 8 bit, 11025Hz,
 *	1 channel, 15382 bytes/channel
 *	Total Size: 1 * 15382 + 4 (header) = 15426 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TenCountSound.wav
 *	Time-stamp: Sat Apr 07 14:51:33 2018
 *	
 **************************************************************/

#ifndef __TENCOUNTSOUNDH__
#define __TENCOUNTSOUNDH__

#define TENCOUNTSOUNDFREQ 11025
#define TENCOUNTSOUNDLEN 15382

extern const unsigned char TenCountSound[15382];

#endif /* __TENCOUNTSOUNDH__ */
