
/**************************************************************
 *	
 *	ThreeCountSound, 8 bit, 11025Hz,
 *	1 channel, 8972 bytes/channel
 *	Total Size: 1 * 8972 + 4 (header) = 9016 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/ThreeCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:35 2018
 *	
 **************************************************************/

#ifndef __THREECOUNTSOUNDH__
#define __THREECOUNTSOUNDH__

#define THREECOUNTSOUNDFREQ 11025
#define THREECOUNTSOUNDLEN 8972

extern const unsigned char ThreeCountSound[8972];

#endif /* __THREECOUNTSOUNDH__ */
