
/**************************************************************
 *	
 *	TwoCountSound, 8 bit, 11025Hz,
 *	1 channel, 8777 bytes/channel
 *	Total Size: 1 * 8777 + 4 (header) = 8821 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/FightSounds/TwoCountSound.wav
 *	Time-stamp: Sat Apr 07 14:50:41 2018
 *	
 **************************************************************/

#ifndef __TWOCOUNTSOUNDH__
#define __TWOCOUNTSOUNDH__

#define TWOCOUNTSOUNDFREQ 11025
#define TWOCOUNTSOUNDLEN 8777

extern const unsigned char TwoCountSound[8777];

#endif /* __TWOCOUNTSOUNDH__ */
