
/**************************************************************
 *	
 *	CornerfaceChase, 8 bit, 11025Hz,
 *	1 channel, 306556 bytes/channel
 *	Total Size: 1 * 306556 + 4 (header) = 306600 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceChase.wav
 *	Time-stamp: Sun Apr 08 16:19:07 2018
 *	
 **************************************************************/

#ifndef __CORNERFACECHASEH__
#define __CORNERFACECHASEH__

#define CORNERFACECHASEFREQ 11025
#define CORNERFACECHASELEN 306556

extern const unsigned char CornerfaceChase[306556];

#endif /* __CORNERFACECHASEH__ */
