
/**************************************************************
 *	
 *	CornerfaceChase2, 8 bit, 11025Hz,
 *	1 channel, 144449 bytes/channel
 *	Total Size: 1 * 144449 + 4 (header) = 144493 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceChase2.wav
 *	Time-stamp: Sat Apr 14 11:35:43 2018
 *	
 **************************************************************/

#ifndef __CORNERFACECHASE2H__
#define __CORNERFACECHASE2H__

#define CORNERFACECHASE2FREQ 11025
#define CORNERFACECHASE2LEN 144449

extern const unsigned char CornerfaceChase2[144449];

#endif /* __CORNERFACECHASE2H__ */
