
/**************************************************************
 *	
 *	CornerfaceAppears, 8 bit, 11025Hz,
 *	1 channel, 151833 bytes/channel
 *	Total Size: 1 * 151833 + 4 (header) = 151877 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CornerfaceAppears.wav
 *	Time-stamp: Sun Apr 08 16:18:59 2018
 *	
 **************************************************************/

#ifndef __CORNERFACEAPPEARSH__
#define __CORNERFACEAPPEARSH__

#define CORNERFACEAPPEARSFREQ 11025
#define CORNERFACEAPPEARSLEN 151833

extern const unsigned char CornerfaceAppears[151833];

#endif /* __CORNERFACEAPPEARSH__ */
