
/**************************************************************
 *	
 *	CorruptionAudio3, 8 bit, 11025Hz,
 *	1 channel, 30208 bytes/channel
 *	Total Size: 1 * 30208 + 4 (header) = 30252 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio3.wav
 *	Time-stamp: Sun Apr 15 02:14:00 2018
 *	
 **************************************************************/

#ifndef __CORRUPTIONAUDIO3H__
#define __CORRUPTIONAUDIO3H__

#define CORRUPTIONAUDIO3FREQ 11025
#define CORRUPTIONAUDIO3LEN 30208

extern const unsigned char CorruptionAudio3[30208];

#endif /* __CORRUPTIONAUDIO3H__ */
