
/**************************************************************
 *	
 *	CorruptionAudio2, 8 bit, 11025Hz,
 *	1 channel, 25703 bytes/channel
 *	Total Size: 1 * 25703 + 4 (header) = 25747 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio2.wav
 *	Time-stamp: Sun Apr 15 02:13:57 2018
 *	
 **************************************************************/

#ifndef __CORRUPTIONAUDIO2H__
#define __CORRUPTIONAUDIO2H__

#define CORRUPTIONAUDIO2FREQ 11025
#define CORRUPTIONAUDIO2LEN 25703

extern const unsigned char CorruptionAudio2[25703];

#endif /* __CORRUPTIONAUDIO2H__ */
