
/**************************************************************
 *	
 *	CorruptionAudio0, 8 bit, 11025Hz,
 *	1 channel, 88832 bytes/channel
 *	Total Size: 1 * 88832 + 4 (header) = 88876 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio0.wav
 *	Time-stamp: Sun Apr 15 02:13:50 2018
 *	
 **************************************************************/

#ifndef __CORRUPTIONAUDIO0H__
#define __CORRUPTIONAUDIO0H__

#define CORRUPTIONAUDIO0FREQ 11025
#define CORRUPTIONAUDIO0LEN 88832

extern const unsigned char CorruptionAudio0[88832];

#endif /* __CORRUPTIONAUDIO0H__ */
