
/**************************************************************
 *	
 *	CorruptionAudio1, 8 bit, 11025Hz,
 *	1 channel, 28672 bytes/channel
 *	Total Size: 1 * 28672 + 4 (header) = 28716 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/CorruptionAudio1.wav
 *	Time-stamp: Sun Apr 15 02:13:52 2018
 *	
 **************************************************************/

#ifndef __CORRUPTIONAUDIO1H__
#define __CORRUPTIONAUDIO1H__

#define CORRUPTIONAUDIO1FREQ 11025
#define CORRUPTIONAUDIO1LEN 28672

extern const unsigned char CorruptionAudio1[28672];

#endif /* __CORRUPTIONAUDIO1H__ */
