
/**************************************************************
 *	
 *	IntroMontage, 8 bit, 11025Hz,
 *	1 channel, 92736 bytes/channel
 *	Total Size: 1 * 92736 + 4 (header) = 92780 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/IntroMontage.wav
 *	Time-stamp: Sat Apr 14 23:55:18 2018
 *	
 **************************************************************/

#ifndef __INTROMONTAGEH__
#define __INTROMONTAGEH__

#define INTROMONTAGEFREQ 11025
#define INTROMONTAGELEN 92736

extern const unsigned char IntroMontage[92736];

#endif /* __INTROMONTAGEH__ */
