
/**************************************************************
 *	
 *	IntroMusic, 8 bit, 11025Hz,
 *	1 channel, 640372 bytes/channel
 *	Total Size: 1 * 640372 + 4 (header) = 640416 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/IntroMusic.wav
 *	Time-stamp: Sat Apr 14 20:27:25 2018
 *	
 **************************************************************/

#ifndef __INTROMUSICH__
#define __INTROMUSICH__

#define INTROMUSICFREQ 11025
#define INTROMUSICLEN 640372

extern const unsigned char IntroMusic[640372];

#endif /* __INTROMUSICH__ */
