
/**************************************************************
 *	
 *	RecordScratch, 8 bit, 11025Hz,
 *	1 channel, 5885 bytes/channel
 *	Total Size: 1 * 5885 + 4 (header) = 5929 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/RecordScratch.wav
 *	Time-stamp: Sun Apr 15 02:48:50 2018
 *	
 **************************************************************/

#ifndef __RECORDSCRATCHH__
#define __RECORDSCRATCHH__

#define RECORDSCRATCHFREQ 11025
#define RECORDSCRATCHLEN 5885

extern const unsigned char RecordScratch[5885];

#endif /* __RECORDSCRATCHH__ */
