
/**************************************************************
 *	
 *	SpreadWings, 8 bit, 11025Hz,
 *	1 channel, 1005408 bytes/channel
 *	Total Size: 1 * 1005408 + 4 (header) = 1005452 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/SpreadWings.wav
 *	Time-stamp: Sat Apr 14 23:55:26 2018
 *	
 **************************************************************/

#ifndef __SPREADWINGSH__
#define __SPREADWINGSH__

#define SPREADWINGSFREQ 11025
#define SPREADWINGSLEN 1005408

extern const unsigned char SpreadWings[1005408];

#endif /* __SPREADWINGSH__ */
