
/**************************************************************
 *	
 *	ThePromise, 8 bit, 11025Hz,
 *	1 channel, 2385697 bytes/channel
 *	Total Size: 1 * 2385697 + 4 (header) = 2385741 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/ThePromise.wav
 *	Time-stamp: Sat Apr 14 11:14:15 2018
 *	
 **************************************************************/

#ifndef __THEPROMISEH__
#define __THEPROMISEH__

#define THEPROMISEFREQ 11025
#define THEPROMISELEN 2385697

extern const unsigned char ThePromise[2385697];

#endif /* __THEPROMISEH__ */
