
/**************************************************************
 *	
 *	VictoryMusic, 8 bit, 11025Hz,
 *	1 channel, 76534 bytes/channel
 *	Total Size: 1 * 76534 + 4 (header) = 76578 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Navi/GameBoiz/Final Project/code/SoundEffects/Music/FinalCutsceneMusic/VictoryMusic.wav
 *	Time-stamp: Wed Apr 11 16:11:18 2018
 *	
 **************************************************************/

#ifndef __VICTORYMUSICH__
#define __VICTORYMUSICH__

#define VICTORYMUSICFREQ 11025
#define VICTORYMUSICLEN 76534

extern const unsigned char VictoryMusic[76534];

#endif /* __VICTORYMUSICH__ */
